//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvvm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliverydetail
    {
        public int ID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<double> AggWeight1 { get; set; }
        public Nullable<double> AggWeight2 { get; set; }
        public Nullable<double> AggWeight3 { get; set; }
        public Nullable<double> AggWeight4 { get; set; }
        public Nullable<double> CementWeight1 { get; set; }
        public Nullable<double> CementWeight2 { get; set; }
        public Nullable<double> CementWeight3 { get; set; }
        public Nullable<double> WaterWeight { get; set; }
        public Nullable<double> AddWeight1 { get; set; }
        public Nullable<double> AddWeight2 { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
