//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvvm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class c : DbContext
    {
        public c()
            : base("name=c")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<Deliverydetail> Deliverydetails { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Name> Names { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TagAddress> TagAddresses { get; set; }
        public virtual DbSet<tbl_per_relationship> tbl_per_relationship { get; set; }
        public virtual DbSet<tbl_permision> tbl_permision { get; set; }
        public virtual DbSet<tbl_permision_detail> tbl_permision_detail { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
    
        public virtual int back_up_database(string namefile)
        {
            var namefileParameter = namefile != null ?
                new ObjectParameter("namefile", namefile) :
                new ObjectParameter("namefile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("back_up_database", namefileParameter);
        }
    
        public virtual int insert_Phan_quyen_Permision_detail(Nullable<int> id_per)
        {
            var id_perParameter = id_per.HasValue ?
                new ObjectParameter("id_per", id_per) :
                new ObjectParameter("id_per", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_Phan_quyen_Permision_detail", id_perParameter);
        }
    
        public virtual int Restore_database(string namefile)
        {
            var namefileParameter = namefile != null ?
                new ObjectParameter("namefile", namefile) :
                new ObjectParameter("namefile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Restore_database", namefileParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> select_check_action_for_login(Nullable<int> id_user, Nullable<bool> licened, string code_action)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("Id_user", id_user) :
                new ObjectParameter("Id_user", typeof(int));
    
            var licenedParameter = licened.HasValue ?
                new ObjectParameter("licened", licened) :
                new ObjectParameter("licened", typeof(bool));
    
            var code_actionParameter = code_action != null ?
                new ObjectParameter("code_action", code_action) :
                new ObjectParameter("code_action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("select_check_action_for_login", id_userParameter, licenedParameter, code_actionParameter);
        }
    
        public virtual ObjectResult<Select_company_Result> Select_company()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_company_Result>("Select_company");
        }
    
        public virtual ObjectResult<Select_Customer_Result> Select_Customer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Customer_Result>("Select_Customer");
        }
    
        public virtual ObjectResult<Select_Delivery_Result> Select_Delivery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Delivery_Result>("Select_Delivery");
        }
    
        public virtual ObjectResult<Select_Delivery_detail_Result> Select_Delivery_detail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Delivery_detail_Result>("Select_Delivery_detail");
        }
    
        public virtual ObjectResult<Select_Driver_Result> Select_Driver()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Driver_Result>("Select_Driver");
        }
    
        public virtual ObjectResult<Nullable<int>> Select_IDuser_with_username_pass(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Select_IDuser_with_username_pass", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Select_name_Result> Select_name()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_name_Result>("Select_name");
        }
    
        public virtual ObjectResult<string> select_Name_action_for_login(string user_name, string password, Nullable<bool> licened, string check_action)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("User_name", user_name) :
                new ObjectParameter("User_name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var licenedParameter = licened.HasValue ?
                new ObjectParameter("licened", licened) :
                new ObjectParameter("licened", typeof(bool));
    
            var check_actionParameter = check_action != null ?
                new ObjectParameter("check_action", check_action) :
                new ObjectParameter("check_action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("select_Name_action_for_login", user_nameParameter, passwordParameter, licenedParameter, check_actionParameter);
        }
    
        public virtual ObjectResult<string> select_Name_permision_for_login(Nullable<int> id_user, Nullable<bool> licened)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("Id_user", id_user) :
                new ObjectParameter("Id_user", typeof(int));
    
            var licenedParameter = licened.HasValue ?
                new ObjectParameter("licened", licened) :
                new ObjectParameter("licened", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("select_Name_permision_for_login", id_userParameter, licenedParameter);
        }
    
        public virtual ObjectResult<Select_PerDetail_DescripionPermision_Result> Select_PerDetail_DescripionPermision(string description)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_PerDetail_DescripionPermision_Result>("Select_PerDetail_DescripionPermision", descriptionParameter);
        }
    
        public virtual ObjectResult<Select_permision_decription_Result> Select_permision_decription()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_permision_decription_Result>("Select_permision_decription");
        }
    
        public virtual ObjectResult<Select_Phan_quyen_ID_Result> Select_Phan_quyen_ID(Nullable<int> id_user)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("Id_user", id_user) :
                new ObjectParameter("Id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Phan_quyen_ID_Result>("Select_Phan_quyen_ID", id_userParameter);
        }
    
        public virtual ObjectResult<Select_Phan_quyen_Permision_Result> Select_Phan_quyen_Permision(string permision)
        {
            var permisionParameter = permision != null ?
                new ObjectParameter("permision", permision) :
                new ObjectParameter("permision", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Phan_quyen_Permision_Result>("Select_Phan_quyen_Permision", permisionParameter);
        }
    
        public virtual ObjectResult<Select_Recipe_Result> Select_Recipe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Recipe_Result>("Select_Recipe");
        }
    
        public virtual ObjectResult<Select_recipe_Id_Result> Select_recipe_Id(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_recipe_Id_Result>("Select_recipe_Id", iDParameter);
        }
    
        public virtual ObjectResult<Select_tagaddress_Result> Select_tagaddress()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_tagaddress_Result>("Select_tagaddress");
        }
    
        public virtual ObjectResult<Select_truck_Result> Select_truck()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_truck_Result>("Select_truck");
        }
    
        public virtual ObjectResult<Select_User_with_username_Result> Select_User_with_username(string username_)
        {
            var username_Parameter = username_ != null ?
                new ObjectParameter("username_", username_) :
                new ObjectParameter("username_", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_User_with_username_Result>("Select_User_with_username", username_Parameter);
        }
    
        public virtual int Update_permision_relaytionship(string description, string id_user)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var id_userParameter = id_user != null ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_permision_relaytionship", descriptionParameter, id_userParameter);
        }
    
        public virtual int update_permistion_detail(Nullable<int> id_pd, string name_action, Nullable<bool> check_action)
        {
            var id_pdParameter = id_pd.HasValue ?
                new ObjectParameter("id_pd", id_pd) :
                new ObjectParameter("id_pd", typeof(int));
    
            var name_actionParameter = name_action != null ?
                new ObjectParameter("name_action", name_action) :
                new ObjectParameter("name_action", typeof(string));
    
            var check_actionParameter = check_action.HasValue ?
                new ObjectParameter("check_action", check_action) :
                new ObjectParameter("check_action", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_permistion_detail", id_pdParameter, name_actionParameter, check_actionParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
