//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvvm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Name
    {
        public int ID { get; set; }
        public string AggName1 { get; set; }
        public string AggName2 { get; set; }
        public string AggName3 { get; set; }
        public string AggName4 { get; set; }
        public string CementName1 { get; set; }
        public string CementName2 { get; set; }
        public string CementName3 { get; set; }
        public string CementName4 { get; set; }
        public string WaterName { get; set; }
        public string AddName1 { get; set; }
        public string AddName2 { get; set; }
    }
}
